### ISSUE TITLE
How can I end a `lsp-devtools agent` process gracefully?

### ISSUE THREAD

**Issue by eliericha** [swyddfa/lsp-devtools#191]
Hello folks,

I'm using `lsp-devtools` through `pytest-lsp`. Basically `pytest-lsp` starts a `lsp-devtools agent` process which intercepts messages. At the end of the test, the client initiates a shutdown sequence which causes the `lsp-devtools` agent to end with the following exception:

```
Traceback (most recent call last):
  File "/home/richa/ancr/venv/bin/lsp-devtools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/richa/ancr/venv/lib/python3.11/site-packages/lsp_devtools/cli.py", line 57, in main
    return parsed_args.run(parsed_args, extra)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richa/ancr/venv/lib/python3.11/site-packages/lsp_devtools/agent/__init__.py", line 58, in run_agent
    asyncio.run(main(args, extra))
  File "/it/local/e3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/it/local/e3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/it/local/e3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/richa/ancr/venv/lib/python3.11/site-packages/lsp_devtools/agent/__init__.py", line 50, in main
    await asyncio.gather(
  File "/home/richa/ancr/venv/lib/python3.11/site-packages/lsp_devtools/agent/agent.py", line 184, in start
    await asyncio.gather(
  File "/home/richa/ancr/venv/lib/python3.11/site-packages/lsp_devtools/agent/agent.py", line 90, in aio_readline
    header = await reader.readline()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/it/local/e3/lib/python3.11/asyncio/streams.py", line 566, in readline
    line = await self.readuntil(sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/it/local/e3/lib/python3.11/asyncio/streams.py", line 658, in readuntil
    await self._wait_for_data('readuntil')
  File "/it/local/e3/lib/python3.11/asyncio/streams.py", line 543, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError: lsp-devtools agent is stopping.
```

This creates noise in my test log: even if a test is successful, I still get this exception which can create confusion.

I'm using `client.shutdown_session()` from `pytest-lsp` to do the shutdown. This sends a `shutdown` request followed by an `exit` notification.

Could the `lsp-devtools` agent detect that as a graceful termination and also terminate gracefully without a scary exception?

Thanks

**Comment by alcarney** [comment]
Assuming your server process exits as expected, `lsp-devtools` is already able to detect it and trigger a shutdown
```python
async def _watch_server_process(self):
    """Once the server process exits, ensure that the agent is also shutdown."""
    ret = await self.server.wait()
    print(f"Server process exited with code: {ret}", file=sys.stderr)
    await self.stop()
```
I expect the issue is that the shutdown process is not as graceful as it could be, or at least `lsp-devtools` needs to be catching that `CancelledError` somewhere... 🤔

**Comment by eliericha** [comment]
I do see the `print` line:

```
Server process exited with code: 0
```

right before the exception backtrace. So I think that the server ended gracefully, but `lsp-devtools` did not.

AFAIU there are 3 concurrent tasks started at this `gather` point: https://github.com/swyddfa/lsp-devtools/blob/develop/lib/lsp-devtools/lsp_devtools/agent/agent.py#L180

- `client_to_server` (the exception is raised in one of these two tasks)
- `server_to_client` (the exception is raised in one of these two tasks)
- `_watch_server_process` which waits for the server process to die

When the server dies, `_watch_server_process` requests cancellation of the other two tasks with the following arguments:

```python
        args = {}
        if sys.version_info >= (3, 9):
            args["msg"] = "lsp-devtools agent is stopping."

        # Cancel the tasks connecting client to server
        for task in self._tasks:
            task.cancel(**args)
```

The above message is the same one that I see in the backtrace. So that cancel must be the reason for the exception in the other tasks.

I'm not an expert in `asyncio`, but perhaps the communication tasks should consider that `CancelledError` is a graceful termination and should mask it?

**Comment by alcarney** [comment]
> I'm not an expert in asyncio, but perhaps the communication tasks should consider that CancelledError is a graceful termination and should mask it?

Yes, I'm hoping putting a try except block around [this line](https://github.com/swyddfa/lsp-devtools/blob/f4558ad38e27f45f8a39388c99267dccf2a762ee/lib/lsp-devtools/lsp_devtools/agent/__init__.py#L59) will be enough to fix the issue

**Comment by alcarney** [comment]
I just released `0.2.4` containing [this change](https://github.com/swyddfa/lsp-devtools/commit/df1ffe34e90710eb1769900f54c5f6661a4db9d4) - does it fix the issue for you?

**Comment by eliericha** [comment]
I tried `0.2.4` and now I have an exception at the point of importing `pytest_lsp` regarding a missing symbol in `lsprotocol.types`. Is it using an unreleased version of `lsprotocol` ?

```
Traceback (most recent call last):
  File "/home/richa/ancr/src/als/./testsuite/testsuite.py", line 11, in <module>
    from drivers.pylsp import PyLSP
  File "/home/richa/ancr/src/als/testsuite/drivers/pylsp.py", line 20, in <module>
    import pytest_lsp
  File "/home/richa/ancr/venv/lib/python3.11/site-packages/pytest_lsp/__init__.py", line 1, in <module>
    from .checks import LspSpecificationWarning
  File "/home/richa/ancr/venv/lib/python3.11/site-packages/pytest_lsp/checks.py", line 264, in <module>
    params: types.WorkspaceConfigurationParams,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lsprotocol.types' has no attribute 'WorkspaceConfigurationParams'
```

And here are my package versions:

```
❯ pip freeze | grep lsp
lsp-devtools==0.2.4
lsprotocol==2024.0.0b1
pytest-lsp==0.4.3
```

**Comment by alcarney** [comment]
> Is it using an unreleased version of `lsprotocol` ?

Ah, sorry I've started the process of upgrading all my projects over to the next major version of [`pygls`](https://github.com/openlawlibrary/pygls) - the underlying LSP protocol framework.
There is a [pre-release](https://github.com/swyddfa/lsp-devtools/releases/tag/pytest-lsp-v1.0.0b2) for `pytest-lsp`, but since `lsp-devtools` is a CLI application I included the migration in a normal release 😅

`pytest-lsp` only uses the CLI interface to `lsp-devtools` so they don't have to be installed together in the same environment - the main thing is to make sure the `lsp-devtools` command is on your $PATH.
I would suggest using something like [pipx](https://pypa.github.io/pipx/) to install `lsp-devtools` into its own isolated environment.

Alternatively, you could try [upgrading](https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/howto/migrate-to-v1.html) to pytest-lsp `v1.0b2` the migration *shouldn't* be too difficult, the biggest change is that a bunch of the LSP type definitions provided by `lsprotocol` have been [renamed](https://pygls.readthedocs.io/en/latest/pygls/howto/migrate-to-v2.html#renamed-lsp-types)

**Comment by eliericha** [comment]
I fixed my setup by removing `lsp-devtools` from my venv, reverting to an older version of `pytest-lsp` and `lsprotocol`, and installing `lsp-devtools 0.2.4` with `pipx`.

I can confirm that now the agent ends gracefully :)

**Comment by alcarney** [comment]
Glad to hear it! :smile:
