### ISSUE TITLE
(pytest-lsp) Handling null Results

### ISSUE THREAD

**Issue by LaurenceWarne** [swyddfa/lsp-devtools#9]
Hi, `pytest-lsp` has made my life a lot easier recently, so thanks for putting it together :slightly_smiling_face: 

For some responses like `HoverResponse` and `CompletionResponse`, a server can return `null` ([link](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover)), and (AFAICS) the pygls `LanguageServer.send_request_async` returns `None` in such circumstances, which causes `pytest_lsp.Client` to throw an exception when it tries to stick the result in for example a `Hover`.  So for example when I `Client.hover_request` at a position where no hovers are the result is:

`TypeError: pygls.lsp.types.language_features.hover.Hover() argument after ** must be a mapping, not NoneType`

Perhaps `None` could be returned?

Let me know if that makes sense, thanks!

**Comment by alcarney** [comment]
Makes total sense, I think returning `None` is a good idea :)

**Comment by LaurenceWarne** [comment]
Cool, I can maybe PR something after #10

**Comment by alcarney** [comment]
Closed by #11
